//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saving.Applications.finance.ws_fin_cashdetail_edit_ctrl {
    
    
    public partial class ws_fin_cashdetail_edit {
        
        /// <summary>
        /// dsUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.finance.ws_fin_cashdetail_edit_ctrl.DsUser dsUser;
        
        /// <summary>
        /// dsMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.finance.ws_fin_cashdetail_edit_ctrl.DsMain dsMain;
        
        /// <summary>
        /// LbInsert1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LbInsert1;
        
        /// <summary>
        /// LbInsert2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LbInsert2;
        
        /// <summary>
        /// dsRecv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.finance.ws_fin_cashdetail_edit_ctrl.DsRecv dsRecv;
        
        /// <summary>
        /// dsPay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.finance.ws_fin_cashdetail_edit_ctrl.DsPay dsPay;

        protected global::Saving.Applications.finance.ws_fin_cashdetail_edit_ctrl.DsProc dsProc;
    }
}
